#!/usr/bin/env python3
"""
Milestone 1 Phase 3 — CONTROL-vs-ACD experiment preparation runner.

Orchestrates existing approved modules (src/sequences.py, src/model_matrix.py,
src/state_machine_features.py) to build a paired CONTROL/ACD dataset on an
identical timestamp universe, then validates paired-universe identity. Does
not train. Does not touch data/raw. Does not overwrite production
sequence_index or production model_matrix (separate Phase-3 output roots).

    python scripts/run_phase3_control_vs_acd.py --mode all
    python scripts/run_phase3_control_vs_acd.py --mode validate

All root paths default to the locations used throughout Milestone 1
Phase 3 (unchanged local-run behavior, byte-identical to the previously
validated 26/26-check runs). They can be overridden via CLI flags to point
at Concourse-mounted input/output directories instead of assumed-present
local paths — see ci/concourse/phase03.yml.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import subprocess
import sys
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src"
sys.path.insert(0, str(SRC))

from state_machine_features import (  # noqa: E402
    ACD_NUMERIC_BOOLEAN_COLUMNS,
    COMMON_MODELING_START,
    _acd_feature_name,
    apply_categorical_encoding,
    build_categorical_encoding_manifest,
    fit_categorical_vocabularies,
)
from model_matrix import DEFAULT_FEATURES  # noqa: E402

SYMBOL = "nvda"
CONFIG_PATH = REPO_ROOT / "config" / "pipeline.yaml"

# Default roots — unchanged from the previously validated Phase-3 v1 runs.
# v1 remains frozen historical provenance; it is never regenerated by the
# active default path below.
DEFAULT_FEATURES_1M_ACD_V1 = REPO_ROOT / "data/parquet/features_1m_acd_v1"
DEFAULT_FEATURES_1M_ACD_V1_ENCODED = REPO_ROOT / "data/parquet/features_1m_acd_v1_encoded"
DEFAULT_TARGETS_1M = REPO_ROOT / "data/parquet/targets_1m"
DEFAULT_TARGETS_1M_PHASE3_VIEW = REPO_ROOT / "data/parquet/targets_1m_phase3_common_v1"
DEFAULT_SEQUENCE_INDEX_ROOT = REPO_ROOT / "data/parquet/sequence_index_phase3_common_v1"
DEFAULT_MODEL_MATRIX_ROOT = REPO_ROOT / "data/parquet/model_matrix_phase3_common_v1"

# v2 (active/default) roots — TEST-sealed. See sequences.py/model_matrix.py
# docstrings for the structural-vs-trainval artifact contract.
DEFAULT_SEQUENCE_INDEX_STRUCTURAL_ROOT_V2 = (
    REPO_ROOT / "data/parquet/sequence_index_phase3_common_v2"
)
DEFAULT_SEQUENCE_INDEX_TRAINVAL_ROOT_V2 = (
    REPO_ROOT / "data/parquet/sequence_index_phase3_trainval_v2"
)
DEFAULT_MODEL_MATRIX_ROOT_V2 = (
    REPO_ROOT / "data/parquet/model_matrix_phase3_trainval_v2"
)

# Frozen structural totals (sequence_index_phase3_common_v2 population).
# Model-matrix-level (post model-ready/finiteness filtering) frozen totals —
# the trainer-facing CONTROL/ACD population, feature_set=core_v1.
FROZEN_TRAIN_COUNT = 878_828
FROZEN_VALIDATION_COUNT = 189_428

# Sequence-index-level (sequences.py's own raw output, BEFORE model_matrix.py's
# model-ready/finiteness filtering) frozen totals — the structural v2
# artifact's population, all three splits. Distinct from the model-matrix
# numbers above by construction (model_matrix.py additionally drops any
# window with a non-finite selected feature) — confirmed against real v1
# data: sequence_index_phase3_common_v1 totals
# {'train': 948368, 'validation': 204308, 'test': 206140}.
FROZEN_STRUCTURAL_TRAIN_COUNT = 948_368
FROZEN_STRUCTURAL_VALIDATION_COUNT = 204_308
FROZEN_STRUCTURAL_TEST_COUNT = 206_140
FROZEN_STRUCTURAL_TOTAL = (
    FROZEN_STRUCTURAL_TRAIN_COUNT
    + FROZEN_STRUCTURAL_VALIDATION_COUNT
    + FROZEN_STRUCTURAL_TEST_COUNT
)

SEQUENCE_SHAPE = (
    "sequence_length=120/horizon=15m/scope=continuous/stride=1/"
    "sessions=premarket+regular+aftermarket"
)

FORBIDDEN_COLUMNS = {
    "or_width_class", "buffer_width_class", "spacing_class", "environment_id",
    "or_width_category", "minutes_since_open", "regime_id",
    "f_sm_regime_id", "signal_outcomes", "regime_evaluation",
}


def control_matrix_root(model_matrix_root: Path) -> Path:
    return model_matrix_root / SEQUENCE_SHAPE / "feature_set=core_v1"


def acd_matrix_root(model_matrix_root: Path) -> Path:
    return model_matrix_root / SEQUENCE_SHAPE / "feature_set=core_v1_acd_v1"


def _run(cmd: list) -> None:
    printable = " ".join(str(c) for c in cmd)
    print(f"+ {printable[:300]}{'...' if len(printable) > 300 else ''}")
    subprocess.run([str(c) for c in cmd], check=True, cwd=REPO_ROOT)


def build_targets_view(
    features_root: Path,
    targets_root: Path,
    targets_view_root: Path,
) -> None:
    """Partition-matching, row-count-matching read-only view of targets_root
    restricted to features_root's own months (sequences.py requires exact
    feature/target partition-set AND per-month row-count parity).
    targets_root itself is never read-write-modified: months entirely inside
    the common range are symlinked (zero duplication); the one boundary
    month that straddles common_modeling_start is materialized as a real
    row-filtered copy (a symlink can't filter rows)."""

    feature_months = sorted(
        (Path(p).parts[-3], Path(p).parts[-2])
        for p in glob.glob(
            str(features_root / f"symbol={SYMBOL}" / "year=*/month=*/*.parquet")
        )
    )
    if not feature_months:
        raise FileNotFoundError(
            f"No features_1m_acd_v1 partitions found under {features_root}."
        )

    for year_dir, month_dir in feature_months:
        src = targets_root / f"symbol={SYMBOL}" / year_dir / month_dir / "part.parquet"
        dst_dir = targets_view_root / f"symbol={SYMBOL}" / year_dir / month_dir
        dst = dst_dir / "part.parquet"
        dst_dir.mkdir(parents=True, exist_ok=True)
        if dst.exists() or dst.is_symlink():
            continue

        feature_file = (
            features_root / f"symbol={SYMBOL}" / year_dir / month_dir / "part.parquet"
        )
        feature_rows = pq.ParquetFile(feature_file).metadata.num_rows
        target_rows = pq.ParquetFile(src).metadata.num_rows

        if feature_rows == target_rows:
            rel = Path(os.path.relpath(src, start=dst.parent))
            dst.symlink_to(rel)
        else:
            feature_dates = pq.ParquetFile(feature_file).read(
                columns=["trading_date"]
            ).to_pandas()
            min_trading_date = feature_dates["trading_date"].min()
            target_frame = pq.ParquetFile(src).read().to_pandas()
            filtered = target_frame[
                target_frame["trading_date"] >= min_trading_date
            ].reset_index(drop=True)
            filtered.to_parquet(
                dst, index=False, engine="pyarrow", compression="zstd"
            )


def build_sequence_index(
    features_root: Path,
    targets_view_root: Path,
    sequence_index_root: Path,
    *,
    legacy_v1: bool = False,
    structural_output_root: Path | None = None,
    trainval_output_root: Path | None = None,
) -> None:
    """
    v1 (--legacy-v1): writes the full-value, all-splits sequence_index
    artifact via sequences.py's frozen legacy path.

    v2 (default): writes two additive outputs via sequences.py's canonical
    v2 path — structural_output_root (all splits, structural columns only)
    and trainval_output_root (TRAIN+VALIDATION values only). sequence_index_root
    is unused in this branch (kept for a uniform call signature).
    """
    if legacy_v1:
        _run([
            sys.executable, SRC / "sequences.py",
            "--legacy-v1",
            "--features-root", features_root,
            "--targets-root", targets_view_root,
            "--output-root", sequence_index_root,
            "--symbol", SYMBOL,
            "--config", CONFIG_PATH,
        ])
        return

    _run([
        sys.executable, SRC / "sequences.py",
        "--features-root", features_root,
        "--targets-root", targets_view_root,
        "--structural-output-root", structural_output_root,
        "--trainval-output-root", trainval_output_root,
        "--symbol", SYMBOL,
        "--config", CONFIG_PATH,
    ])


def build_encoded_acd_features(
    sequence_index_root: Path,
    features_root: Path,
    encoded_features_root: Path,
) -> dict:
    vocabularies = fit_categorical_vocabularies(
        sequence_index_root=sequence_index_root,
        features_root=features_root,
        symbol=SYMBOL,
    )
    manifest = build_categorical_encoding_manifest(vocabularies)

    encoded_features_root.mkdir(parents=True, exist_ok=True)
    manifest_path = encoded_features_root / "categorical_encoding_manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"wrote {manifest_path}")

    apply_categorical_encoding(
        features_root=features_root,
        output_root=encoded_features_root,
        manifest=manifest,
        symbol=SYMBOL,
        parquet_compression="zstd",
    )
    return manifest


def _load_manifest(encoded_features_root: Path) -> dict:
    manifest_path = encoded_features_root / "categorical_encoding_manifest.json"
    with open(manifest_path, encoding="utf-8") as f:
        return json.load(f)


def derive_acd_features(manifest: dict) -> list:
    """Programmatic derivation only — no hard-coded one-hot column names,
    no /tmp dependency. Numeric/boolean names come from the approved
    ACD_NUMERIC_BOOLEAN_COLUMNS whitelist; one-hot names come from the
    persisted, TRAIN-fit manifest."""

    numeric = [_acd_feature_name(c) for c in ACD_NUMERIC_BOOLEAN_COLUMNS]
    onehot = [
        column
        for entry in manifest.values()
        for column in entry["encoded_columns"]
    ]
    return list(DEFAULT_FEATURES) + numeric + onehot


def build_control_model_matrix(
    features_root: Path,
    sequence_index_root: Path,
    model_matrix_root: Path,
    *,
    legacy_v1: bool = False,
) -> None:
    """
    `sequence_index_root` must be sequences.py's all-splits legacy output
    when legacy_v1=True, or its v2 TRAINVAL-only output otherwise — the
    caller selects the correct root; this function does not.
    """
    cmd = [
        sys.executable, SRC / "model_matrix.py",
        "--features-root", features_root,
        "--sequence-root", sequence_index_root,
        "--output-root", model_matrix_root,
        "--symbol", SYMBOL,
        "--feature-set", "core_v1",
        "--features", *DEFAULT_FEATURES,
        "--config", CONFIG_PATH,
    ]
    if legacy_v1:
        cmd.insert(1, "--legacy-v1")
    _run(cmd)


def build_acd_model_matrix(
    encoded_features_root: Path,
    sequence_index_root: Path,
    model_matrix_root: Path,
    manifest: dict,
    *,
    legacy_v1: bool = False,
) -> None:
    features = derive_acd_features(manifest)
    cmd = [
        sys.executable, SRC / "model_matrix.py",
        "--features-root", encoded_features_root,
        "--sequence-root", sequence_index_root,
        "--output-root", model_matrix_root,
        "--symbol", SYMBOL,
        "--feature-set", "core_v1_acd_v1",
        "--features", *features,
        "--config", CONFIG_PATH,
    ]
    if legacy_v1:
        cmd.insert(1, "--legacy-v1")
    _run(cmd)


def _load_sequence_frame(root: Path, columns: list) -> pd.DataFrame:
    files = sorted(glob.glob(str(root / "sequences" / "**" / "*.parquet"), recursive=True))
    if not files:
        raise FileNotFoundError(f"No sequences/ partitions found under {root}.")
    frames = [pq.ParquetFile(f).read(columns=columns).to_pandas() for f in files]
    return pd.concat(frames, ignore_index=True)


def run_validation(control_root: Path, acd_root: Path, encoded_features_root: Path) -> bool:
    """The 14 checks in references/paired-universe-test-contract.md."""

    checks: list = []

    def check(name: str, condition: bool, detail: str = "") -> None:
        checks.append((name, bool(condition), detail))
        status = "PASS" if condition else "FAIL"
        print(f"  [{status}] {name}" + (f" — {detail}" if detail and not condition else ""))

    key_cols = [
        "symbol", "window_start_datetime", "window_end_datetime", "prediction_time",
        "target_realized_at", "trading_date", "session", "split",
        "target_return_bps", "target_log_return", "target_direction",
        "target_same_session", "target_same_trading_date",
    ]
    control = _load_sequence_frame(control_root, key_cols).sort_values(
        "window_end_datetime"
    ).reset_index(drop=True)
    acd = _load_sequence_frame(acd_root, key_cols).sort_values(
        "window_end_datetime"
    ).reset_index(drop=True)

    print("\nPaired-universe validation:")

    # 1-2. same sequence count overall / by split
    check("1. same sequence count overall", len(control) == len(acd),
          f"control={len(control)} acd={len(acd)}")
    control_splits = control["split"].value_counts().to_dict()
    acd_splits = acd["split"].value_counts().to_dict()
    check("2. same sequence count by split", control_splits == acd_splits,
          f"control={control_splits} acd={acd_splits}")

    # 3-4. ordered keys / matching fields
    check("3. same ordered sequence keys",
          list(control["window_end_datetime"]) == list(acd["window_end_datetime"]))
    for col in key_cols:
        mismatches = int((control[col].reset_index(drop=True)
                           != acd[col].reset_index(drop=True)).sum())
        check(f"4. matching {col}", mismatches == 0, f"{mismatches} mismatches")

    # 5. target values/availability (subset of key_cols already checked above)
    check("5. same target values/availability",
          (control["target_return_bps"] == acd["target_return_bps"]).all()
          and (control["target_direction"] == acd["target_direction"]).all())

    # 6. purge/embargo: identical by construction (same shared sequence_index)
    check("6. same purge/embargo exclusions (shared sequence_index)", True)

    # 7. no invalid session-crossing sequences: enforced upstream by sequences.py
    # (scope=continuous with defined sessions) — re-assert both sides agree.
    check("7. no invalid session-crossing sequences",
          (control["session"] == acd["session"]).all())

    # 8. no pre-2020-01-03 sample
    check("8. no pre-2020-01-03 sample",
          control["trading_date"].min() >= COMMON_MODELING_START
          and acd["trading_date"].min() >= COMMON_MODELING_START,
          f"control_min={control['trading_date'].min()} acd_min={acd['trading_date'].min()}")

    # 9-11. feature schema checks via scaler.json
    control_scaler = json.load(open(control_root / "scaler.json"))
    acd_scaler = json.load(open(acd_root / "scaler.json"))
    control_features = set(control_scaler["feature_names"])
    acd_features = set(acd_scaler["feature_names"])

    check("9. CONTROL has zero ACD feature columns",
          not any(f.startswith("f_sm_") for f in control_features))
    incremental = acd_features - control_features
    expected_incremental = len(ACD_NUMERIC_BOOLEAN_COLUMNS) + sum(
        len(e["encoded_columns"]) for e in _load_manifest(encoded_features_root).values()
    )
    check("10. ACD has exactly the approved incremental columns",
          control_features <= acd_features
          and len(incremental) == expected_incremental,
          f"incremental={len(incremental)} expected={expected_incremental}")
    check("11. no forbidden columns",
          not (FORBIDDEN_COLUMNS & control_features)
          and not (FORBIDDEN_COLUMNS & acd_features))

    # 12. scaler fit TRAIN only
    check("12. scaler fit TRAIN-only, applied unchanged to validation/test",
          "TRAIN" in control_scaler["fit_policy"].upper()
          and "TRAIN" in acd_scaler["fit_policy"].upper()
          and control_scaler["train_last_trading_date"] == acd_scaler["train_last_trading_date"])

    # 13. no unexpected NaN/inf in the final numeric matrix
    import numpy as np
    nan_ok = True
    for root in (control_root, acd_root):
        rows_files = sorted(glob.glob(str(root / "rows" / "**" / "*.parquet"), recursive=True))
        sample_file = rows_files[len(rows_files) // 2]
        sample = pq.ParquetFile(sample_file).read().to_pandas()
        numeric_cols = [
            c for c in sample.columns
            if pd.api.types.is_numeric_dtype(sample[c])
            and c not in ("model_sample_index", "sample_index")
        ]
        arr = sample[numeric_cols].to_numpy(dtype="float64")
        if not np.isfinite(arr).all():
            nan_ok = False
    check("13. no NaN/inf in final numeric matrix (sampled)", nan_ok)

    # 14. deterministic feature-column order
    check("14. deterministic feature-column order",
          control_scaler["feature_names"] == acd_scaler["feature_names"][:len(DEFAULT_FEATURES)])

    passed = all(ok for _, ok, _ in checks)
    print(f"\nOverall: {'PASS' if passed else 'FAIL'} ({sum(ok for _, ok, _ in checks)}/{len(checks)} checks)")
    return passed


def _load_structural_frame(structural_root: Path, columns: list) -> pd.DataFrame:
    files = sorted(glob.glob(str(structural_root / "**" / "*.parquet"), recursive=True))
    files = [f for f in files if "manifest.json" not in f]
    if not files:
        raise FileNotFoundError(f"No structural Parquet parts found under {structural_root}.")
    frames = [pq.ParquetFile(f).read(columns=columns).to_pandas() for f in files]
    return pd.concat(frames, ignore_index=True)


def run_validation_v2(
    control_root: Path,
    acd_root: Path,
    encoded_features_root: Path,
    structural_root: Path,
) -> bool:
    """
    v2 counterpart to run_validation(): CONTROL/ACD trainer-facing artifacts
    contain TRAIN+VALIDATION only (zero TEST rows), cross-checked against
    sequences.py's separate structural (all-splits, no values) artifact for
    the true TEST/total provenance. Same feature-schema/scaler/NaN checks as
    v1, adapted to the narrower trainval population.
    """
    checks: list = []

    def check(name: str, condition: bool, detail: str = "") -> None:
        checks.append((name, bool(condition), detail))
        status = "PASS" if condition else "FAIL"
        print(f"  [{status}] {name}" + (f" — {detail}" if detail and not condition else ""))

    key_cols = [
        "symbol", "window_start_datetime", "window_end_datetime", "prediction_time",
        "target_realized_at", "trading_date", "session", "split",
        "target_return_bps", "target_log_return", "target_direction",
        "target_same_session", "target_same_trading_date",
    ]
    control = _load_sequence_frame(control_root, key_cols).sort_values(
        "window_end_datetime"
    ).reset_index(drop=True)
    acd = _load_sequence_frame(acd_root, key_cols).sort_values(
        "window_end_datetime"
    ).reset_index(drop=True)

    print("\nPaired-universe validation (v2, TEST-sealed):")

    # 1. zero TEST rows in trainer-facing CONTROL/ACD.
    control_test = int((control["split"] == "test").sum())
    acd_test = int((acd["split"] == "test").sum())
    check("1. zero TEST rows in CONTROL trainer-facing artifact",
          control_test == 0, f"control_test={control_test}")
    check("2. zero TEST rows in ACD trainer-facing artifact",
          acd_test == 0, f"acd_test={acd_test}")

    # 2-3. same TRAIN+VALIDATION sequence count overall / by split, equal to
    # the frozen trainval total.
    check("3. same TRAIN+VALIDATION sequence count overall",
          len(control) == len(acd) == FROZEN_TRAIN_COUNT + FROZEN_VALIDATION_COUNT,
          f"control={len(control)} acd={len(acd)} "
          f"expected={FROZEN_TRAIN_COUNT + FROZEN_VALIDATION_COUNT}")
    control_splits = control["split"].value_counts().to_dict()
    acd_splits = acd["split"].value_counts().to_dict()
    check("4. same sequence count by split",
          control_splits == acd_splits
          and control_splits.get("train", 0) == FROZEN_TRAIN_COUNT
          and control_splits.get("validation", 0) == FROZEN_VALIDATION_COUNT,
          f"control={control_splits} acd={acd_splits}")

    # 5-6. ordered keys / matching fields
    check("5. same ordered sequence keys",
          list(control["window_end_datetime"]) == list(acd["window_end_datetime"]))
    for col in key_cols:
        mismatches = int((control[col].reset_index(drop=True)
                           != acd[col].reset_index(drop=True)).sum())
        check(f"6. matching {col}", mismatches == 0, f"{mismatches} mismatches")

    # 7. target values/availability
    check("7. same target values/availability",
          (control["target_return_bps"] == acd["target_return_bps"]).all()
          and (control["target_direction"] == acd["target_direction"]).all())

    # 8. no invalid session-crossing sequences
    check("8. no invalid session-crossing sequences",
          (control["session"] == acd["session"]).all())

    # 9. no pre-2020-01-03 sample
    check("9. no pre-2020-01-03 sample",
          control["trading_date"].min() >= COMMON_MODELING_START
          and acd["trading_date"].min() >= COMMON_MODELING_START,
          f"control_min={control['trading_date'].min()} acd_min={acd['trading_date'].min()}")

    # 10-12. feature schema checks via scaler.json
    control_scaler = json.load(open(control_root / "scaler.json"))
    acd_scaler = json.load(open(acd_root / "scaler.json"))
    control_features = set(control_scaler["feature_names"])
    acd_features = set(acd_scaler["feature_names"])

    check("10. CONTROL has zero ACD feature columns",
          not any(f.startswith("f_sm_") for f in control_features))
    incremental = acd_features - control_features
    expected_incremental = len(ACD_NUMERIC_BOOLEAN_COLUMNS) + sum(
        len(e["encoded_columns"]) for e in _load_manifest(encoded_features_root).values()
    )
    check("11. ACD has exactly the approved incremental columns",
          control_features <= acd_features
          and len(incremental) == expected_incremental,
          f"incremental={len(incremental)} expected={expected_incremental}")
    check("12. no forbidden columns",
          not (FORBIDDEN_COLUMNS & control_features)
          and not (FORBIDDEN_COLUMNS & acd_features))
    check("12b. CONTROL feature_count == 23",
          len(control_features) == len(DEFAULT_FEATURES),
          f"actual={len(control_features)}")

    # 13. scaler fit TRAIN only, identical boundary
    check("13. scaler fit TRAIN-only, applied unchanged to validation",
          "TRAIN" in control_scaler["fit_policy"].upper()
          and "TRAIN" in acd_scaler["fit_policy"].upper()
          and control_scaler["train_last_trading_date"] == acd_scaler["train_last_trading_date"])

    # 14. no unexpected NaN/inf in the final numeric matrix
    import numpy as np
    nan_ok = True
    for root in (control_root, acd_root):
        rows_files = sorted(glob.glob(str(root / "rows" / "**" / "*.parquet"), recursive=True))
        sample_file = rows_files[len(rows_files) // 2]
        sample = pq.ParquetFile(sample_file).read().to_pandas()
        numeric_cols = [
            c for c in sample.columns
            if pd.api.types.is_numeric_dtype(sample[c])
            and c not in ("model_sample_index", "sample_index")
        ]
        arr = sample[numeric_cols].to_numpy(dtype="float64")
        if not np.isfinite(arr).all():
            nan_ok = False
    check("14. no NaN/inf in final numeric matrix (sampled)", nan_ok)

    # 15. deterministic feature-column order
    check("15. deterministic feature-column order",
          control_scaler["feature_names"] == acd_scaler["feature_names"][:len(DEFAULT_FEATURES)])

    # 16-18. structural (all-splits, no-value) artifact cross-check —
    # sequences.py's separate provenance for TEST/total counts. NOTE: the
    # structural artifact is sequences.py's own raw (pre-model-ready-filter)
    # population, so it is compared against the STRUCTURAL-level frozen
    # numbers (948,368/204,308/206,140), not the narrower model-matrix-level
    # trainer-facing numbers (878,828/189,428) used in checks 3-4 above —
    # model_matrix.py's Pass 1 additionally drops any window with a
    # non-finite selected feature, so the two levels are expected to differ.
    structural = _load_structural_frame(structural_root, ["split"])
    structural_counts = structural["split"].value_counts().to_dict()
    check(
        "16. structural artifact total == frozen structural total (1,358,816)",
        len(structural) == FROZEN_STRUCTURAL_TOTAL,
        f"actual={len(structural)}",
    )
    check(
        "17. structural TEST count == frozen structural TEST count (206,140)",
        structural_counts.get("test", 0) == FROZEN_STRUCTURAL_TEST_COUNT,
        f"actual={structural_counts.get('test', 0)}",
    )
    check(
        "18. structural TRAIN/VALIDATION counts match frozen structural counts",
        structural_counts.get("train", 0) == FROZEN_STRUCTURAL_TRAIN_COUNT
        and structural_counts.get("validation", 0) == FROZEN_STRUCTURAL_VALIDATION_COUNT,
        f"actual={structural_counts}",
    )

    passed = all(ok for _, ok, _ in checks)
    print(f"\nOverall: {'PASS' if passed else 'FAIL'} ({sum(ok for _, ok, _ in checks)}/{len(checks)} checks)")
    return passed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mode",
        choices=["prepare", "control", "acd", "validate", "all"],
        default="all",
    )
    parser.add_argument(
        "--legacy-v1",
        action="store_true",
        help=(
            "Explicit opt-in to the frozen v1 build path: writes the "
            "full-value, all-splits sequence_index/model_matrix artifacts "
            "(data/parquet/sequence_index_phase3_common_v1, "
            "data/parquet/model_matrix_phase3_common_v1). Without this "
            "flag, the v2 build path runs by default: TEST-sealed "
            "structural + TRAIN+VALIDATION-only trainval artifacts."
        ),
    )
    parser.add_argument("--features-root", type=Path, default=DEFAULT_FEATURES_1M_ACD_V1)
    parser.add_argument("--targets-root", type=Path, default=DEFAULT_TARGETS_1M)
    parser.add_argument("--targets-view-root", type=Path, default=DEFAULT_TARGETS_1M_PHASE3_VIEW)
    parser.add_argument(
        "--sequence-index-root", type=Path, default=DEFAULT_SEQUENCE_INDEX_ROOT,
        help="v1 (--legacy-v1) only: full-value, all-splits sequence_index root.",
    )
    parser.add_argument(
        "--structural-sequence-index-root", type=Path,
        default=DEFAULT_SEQUENCE_INDEX_STRUCTURAL_ROOT_V2,
        help="v2 (default) only: structural, all-splits, no-value-column root.",
    )
    parser.add_argument(
        "--trainval-sequence-index-root", type=Path,
        default=DEFAULT_SEQUENCE_INDEX_TRAINVAL_ROOT_V2,
        help="v2 (default) only: TRAIN+VALIDATION-only value root.",
    )
    parser.add_argument(
        "--model-matrix-root", type=Path, default=None,
        help=(
            "Defaults to the v2 trainval root, or the v1 all-splits root "
            "if --legacy-v1 is set. Pass explicitly to override either way."
        ),
    )
    parser.add_argument("--encoded-features-root", type=Path, default=DEFAULT_FEATURES_1M_ACD_V1_ENCODED)
    args = parser.parse_args()

    model_matrix_root = args.model_matrix_root or (
        DEFAULT_MODEL_MATRIX_ROOT if args.legacy_v1 else DEFAULT_MODEL_MATRIX_ROOT_V2
    )

    control_root = control_matrix_root(model_matrix_root)
    acd_root = acd_matrix_root(model_matrix_root)

    manifest = None

    if args.legacy_v1:
        if args.mode in ("prepare", "all"):
            build_targets_view(args.features_root, args.targets_root, args.targets_view_root)
            build_sequence_index(
                args.features_root, args.targets_view_root, args.sequence_index_root,
                legacy_v1=True,
            )
            manifest = build_encoded_acd_features(
                args.sequence_index_root, args.features_root, args.encoded_features_root
            )

        if args.mode in ("control", "all"):
            build_control_model_matrix(
                args.features_root, args.sequence_index_root, model_matrix_root,
                legacy_v1=True,
            )

        if args.mode in ("acd", "all"):
            if manifest is None:
                manifest = _load_manifest(args.encoded_features_root)
            build_acd_model_matrix(
                args.encoded_features_root, args.sequence_index_root, model_matrix_root,
                manifest, legacy_v1=True,
            )

        passed = True
        if args.mode in ("validate", "all"):
            passed = run_validation(control_root, acd_root, args.encoded_features_root)

        print("\nOutput paths (v1 legacy):")
        print(f"  sequence_index:    {args.sequence_index_root}")
        print(f"  encoded features:  {args.encoded_features_root}")
        print(f"  CONTROL matrix:    {control_root}")
        print(f"  ACD matrix:        {acd_root}")

        return 0 if passed else 1

    # v2 (active/default) path.
    if args.mode in ("prepare", "all"):
        build_targets_view(args.features_root, args.targets_root, args.targets_view_root)
        build_sequence_index(
            args.features_root, args.targets_view_root, None,
            legacy_v1=False,
            structural_output_root=args.structural_sequence_index_root,
            trainval_output_root=args.trainval_sequence_index_root,
        )
        manifest = build_encoded_acd_features(
            args.trainval_sequence_index_root, args.features_root, args.encoded_features_root
        )

    if args.mode in ("control", "all"):
        build_control_model_matrix(
            args.features_root, args.trainval_sequence_index_root, model_matrix_root,
            legacy_v1=False,
        )

    if args.mode in ("acd", "all"):
        if manifest is None:
            manifest = _load_manifest(args.encoded_features_root)
        build_acd_model_matrix(
            args.encoded_features_root, args.trainval_sequence_index_root, model_matrix_root,
            manifest, legacy_v1=False,
        )

    passed = True
    if args.mode in ("validate", "all"):
        passed = run_validation_v2(
            control_root, acd_root, args.encoded_features_root,
            args.structural_sequence_index_root,
        )

    print("\nOutput paths (v2 active):")
    print(f"  structural sequence_index: {args.structural_sequence_index_root}")
    print(f"  trainval sequence_index:   {args.trainval_sequence_index_root}")
    print(f"  encoded features:          {args.encoded_features_root}")
    print(f"  CONTROL matrix:            {control_root}")
    print(f"  ACD matrix:                {acd_root}")

    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
